import type { StoreMigration } from '@nestjs/store-kit/postgres';

/**
 * The store's tables. Times are epoch milliseconds (`bigint`) from the producers' and the relays' clocks; payloads,
 * headers and failure histories are JSON (`jsonb`), a `null` payload SQL `NULL`.
 */
export const initialMigration: StoreMigration = {
  version: 1,
  name: 'initial',
  up: (s) => [
    // A message until it's published or dead-lettered. `seq` is its place in its key: numbered at insert, in commit
    // order (add() takes the key's lock first), never the producers' ids or clocks.
    `CREATE TABLE ${s}.messages (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL UNIQUE,
  topic text NOT NULL,
  payload jsonb,
  headers jsonb NOT NULL,
  key text,
  created_at bigint NOT NULL,
  available_at bigint NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  history jsonb NOT NULL DEFAULT '[]',
  lease_owner text,
  lease_until bigint
)`,
    // A dead letter keeps its message's `seq`, so a requeue puts it back at its place in its key.
    `CREATE TABLE ${s}.dead_letters (
  id text PRIMARY KEY,
  seq bigint NOT NULL,
  topic text NOT NULL,
  payload jsonb,
  headers jsonb NOT NULL,
  key text,
  created_at bigint NOT NULL,
  attempts integer NOT NULL,
  last_error text,
  history jsonb NOT NULL,
  reason text NOT NULL,
  failed_at bigint NOT NULL
)`,
    // One record per consumer and message: the key two deliveries of a message meet at.
    `CREATE TABLE ${s}.inbox (
  consumer text NOT NULL,
  message_id text NOT NULL,
  processed_at bigint NOT NULL,
  PRIMARY KEY (consumer, message_id)
)`,
    // What a claim probes for a keyed message: the older messages of its key. Messages without a key need no entry.
    `CREATE INDEX messages_key_seq ON ${s}.messages (key, seq) WHERE key IS NOT NULL`,
    // What listing and purging dead letters by topic look for.
    `CREATE INDEX dead_letters_topic_failed_at ON ${s}.dead_letters (topic, failed_at)`,
    // What pruning the inbox looks for.
    `CREATE INDEX inbox_processed_at ON ${s}.inbox (processed_at)`,
  ],
};
